# Generated by Django 4.1.3 on 2022-11-01 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('gender', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='sales_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('gender', models.BooleanField()),
                ('date_hired', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sales_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_order_taken', models.IntegerField()),
                ('purchase_order_number', models.IntegerField()),
                ('credit_card_number', models.IntegerField()),
                ('credit_card_expire_date', models.DateField()),
                ('name_on_card', models.CharField(max_length=40)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='sales_app.customer')),
                ('sales_person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_person', to='sales_app.sales_person')),
            ],
        ),
        migrations.CreateModel(
            name='sales_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('taxable', models.IntegerField()),
                ('sales_tax_rate', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='sales_app.item')),
                ('sales_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order', to='sales_app.sales_order')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('supplier', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='sales_app.product_type')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='sales_app.product'),
        ),
    ]
