# Generated by Django 4.1.3 on 2022-11-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='sales_person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sales_person',
            name='gender',
        ),
        migrations.DeleteModel(
            name='product_type',
        ),
    ]
