# Generated by Django 4.1.3 on 2022-11-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0004_rename_product_id_item_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sales_item',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='sales_item',
            old_name='sales_order_id',
            new_name='sales_order',
        ),
        migrations.RenameField(
            model_name='sales_order',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='sales_order',
            old_name='sales_person_name',
            new_name='sales_person',
        ),
    ]
